### ISSUE TITLE
Docker deploy documentation seems to be corrupt

### ISSUE THREAD

**Issue by beanformer** [metadatacenter/cedar-docker-deploy#13]
When following the link, the format of the page seems to be corrupt and additionally, a 404 is mentioned in the content area.

**Comment by marcosmro** [comment]
I've fixed the link (it now points to https://metadatacenter.readthedocs.io/en/latest/install-docker-eval/intro.html).

Note that we are not currently maintaining our Docker documentation/installation so, please, use the [Developer Install Guide](https://metadatacenter.readthedocs.io/en/latest/install-developer/intro.html) if possible.

As an alternative, if you want to use the CEDAR system available at https://cedar.metadatacenter.org/, you are welcome to do so. It is free and you can self-register.
